{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vrt.fullname" . }}-migration
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vrt.labels" . | nindent 4 }}
    app: migration
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "vrt.selectorLabels" . | nindent 8 }}
        app: migration
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vrt.serviceAccountName" . }}
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          while ! nc -z {{ include "vrt.postgres.host" . }} {{ .Values.postgres.port }}; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is up"
      containers:
      - name: migration
        image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
        imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ include "vrt.postgres.host" . }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "vrt.fullname" . }}-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "vrt.fullname" . }}-secret
              key: POSTGRES_PASSWORD
{{- end }}
