apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vrt.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vrt.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.api.secrets.postgresPassword | quote }}
  {{- if .Values.ldap.enabled }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  {{- end }}
  {{- if .Values.awsS3.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsS3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsS3.secretAccessKey | quote }}
  {{- end }}
