{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vrt.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vrt.labels" . | nindent 4 }}
    app: postgres
  {{- with .Values.postgres.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgres.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "vrt.selectorLabels" . | nindent 4 }}
    app: postgres
{{- end }}
